server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id:
            product
          uri:
            lb://product
          predicates:
            - Path=/categories/**
        - id:
            payment
          uri:
            lb://payment
          predicates:
            - Path=/microservice1/payments/**
          filters:
            - RewritePath=/microservice1/payments/(?<segment>.*), /payments/$\{segment}
        - id:
            receipt
          uri:
            lb://payment
          predicates:
            - Path=/microservice1/receipts/**
          filters:
            - RewritePath=/microservice1/receipts/(?<segment>.*), /receipts/$\{segment}