server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoseR200/Microservices.git
          search-paths: config-data
  security:
    user:
      name: root
      password: s3cr3t